import argparse
import json
import os
from datetime import datetime
from pathlib import Path

import numpy as np
import torch
from config import BrainCodingConfig
from data.dataset import create_dataloaders
from experiment_runner import ExperimentRunner
from models.baseline_model import DenseBaselineModel
from models.brain_model import BrainCodingModel
from training.trainer import BrainTrainer


def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def parse_args():
    parser = argparse.ArgumentParser(description="BrainCodeNet Training & Experiments")

    # 실행 모드 선택
    parser.add_argument(
        "--mode",
        type=str,
        default="train",
        choices=["train", "experiments", "table-only"],
        help=(
            "train: 단일 모델 학습 | "
            "experiments: 전체 비교+Ablation 실행 | "
            "table-only: 저장된 결과로 테이블만 생성"
        ),
    )

    # 학습 옵션
    parser.add_argument("--experiment", type=str, default="braincodeNet_default")
    parser.add_argument("--resume", type=str, default=None)
    parser.add_argument("--no-amp", action="store_true")
    parser.add_argument("--multi-gpu", action="store_true")

    # 테이블 생성 옵션
    parser.add_argument(
        "--results-json",
        type=str,
        default="wiki/sources/all_results.json",
        help="table-only 모드에서 사용할 결과 JSON",
    )

    return parser.parse_args()


def check_cuda_environment():
    """CUDA 환경 사전 점검"""
    print(f"\n{'=' * 40}")
    print("CUDA Environment Check")
    print(f"{'=' * 40}")
    print(f"PyTorch version: {torch.__version__}")
    print(f"CUDA available: {torch.cuda.is_available()}")

    if torch.cuda.is_available():
        print(f"CUDA version: {torch.version.cuda}")
        print(f"GPU count: {torch.cuda.device_count()}")
        for i in range(torch.cuda.device_count()):
            prop = torch.cuda.get_device_properties(i)
            print(f"  GPU {i}: {prop.name} | {prop.total_memory / 1e9:.1f} GB")
    print(f"{'=' * 40}\n")


def generate_latex_table(results: list, output_path: str):
    """
    실험 결과를 LaTeX 테이블로 변환하여 wiki/sources 에 저장

    Args:
        results: ExperimentRunner.run_all_experiments() 반환값
        output_path: LaTeX 파일 저장 경로
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # 테이블 행 생성
    latex_rows = []
    for r in results:
        model_name = r["model"]

        # BrainCodeNet 은 볼드체로 강조
        if "BrainCodeNet" in model_name:
            model_name = f"\\textbf{{{model_name}}}"

        row = (
            f"{model_name} & "
            f"{r['top1_accuracy']:.3f} & "
            f"{r['avg_sparsity']:.3f} & "
            f"{r['energy_reduction']:.1f}$\\times$ \\\\"
        )
        latex_rows.append(row)

    # LaTeX 테이블 생성
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    latex_content = f"""% Auto-generated by BrainCodeNet experiments
% Timestamp: {timestamp}
% DO NOT EDIT MANUALLY - Regenerate with: python main.py --mode experiments

\\begin{{table}}[h]
\\centering
\\caption{{Performance and Energy Metrics Comparison for Code Generation}}
\\label{{tab:braincodeNet_results}}
\\begin{{tabular}}{{lccc}}
\\toprule
\\textbf{{Model}} & \\textbf{{Top-1 Accuracy}} & \\textbf{{Sparsity}} & \\textbf{{Energy Reduction}} \\\\
\\midrule
{chr(10).join(latex_rows)}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""

    # 파일 저장
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(latex_content)

    # CSV 백업도 생성
    try:
        import pandas as pd

        df = pd.DataFrame(results)
        csv_path = output_path.replace(".tex", ".csv")
        df.to_csv(csv_path, index=False)
    except ImportError:
        csv_path = None

    print(f"\n[성공] LaTeX 테이블 생성 완료:")
    print(f"  - LaTeX: {output_path}")
    if csv_path:
        print(f"  - CSV: {csv_path}")
    print("\n생성된 LaTeX 테이블:")
    print("=" * 60)
    print(latex_content)
    print("=" * 60)


def mode_train(args, config):
    """단일 모델 학습 모드 (기존 기능 유지)"""
    config.experiment_name = args.experiment
    config.resume_from = args.resume
    config.use_amp = not args.no_amp
    config.multi_gpu = args.multi_gpu

    set_seed(config.seed)

    train_loader, val_loader, tokenizer = create_dataloaders(config)
    model = BrainCodingModel(config)
    trainer = BrainTrainer(model, train_loader, val_loader, config)

    try:
        trainer.train()
    except torch.cuda.OutOfMemoryError:
        print("[ERROR] CUDA OOM - batch_size 를 줄여서 재시도하세요")
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        raise


def mode_experiments(config):
    """전체 실험 자동화 모드"""
    print("BrainCodeNet 전체 실험 파이프라인을 시작합니다...")
    print("예상 소요 시간: 약 2-3 시간 (GPU 환경 기준)")

    # 실험 실행
    runner = ExperimentRunner(config)
    all_results = runner.run_all_experiments()

    # LaTeX 테이블 생성
    latex_path = config.get_latex_table_path()
    generate_latex_table(all_results, latex_path)

    print(f"\n실험 완료! 다음 파일들이 생성되었습니다:")
    print(f"  - 논문용 테이블: {latex_path}")
    print(f"  - 전체 결과 JSON: {config.get_wiki_sources_dir()}/all_results.json")


def mode_table_only(args):
    """저장된 결과로 테이블만 재생성"""
    results_path = Path(args.results_json)

    if not results_path.exists():
        print(f"[ERROR] 결과 파일이 없습니다: {results_path}")
        print("먼저 --mode experiments 를 실행해주세요")
        return

    with open(results_path, "r") as f:
        all_results = json.load(f)

    print(f"[Info] {len(all_results)} 개 실험 결과를 로드했습니다")

    # LaTeX 테이블 생성
    config = BrainCodingConfig()
    latex_path = config.get_latex_table_path()
    generate_latex_table(all_results, latex_path)


def main():
    args = parse_args()
    check_cuda_environment()

    config = BrainCodingConfig()

    if args.mode == "train":
        mode_train(args, config)

    elif args.mode == "experiments":
        mode_experiments(config)

    elif args.mode == "table-only":
        mode_table_only(args)


if __name__ == "__main__":
    main()
